### ISSUE TITLE
Server is down and thus a lot of stuff seems to not be working

### ISSUE THREAD

**Issue by Jacalz** [MrBrax/mulle.js#1]
Hello MrBrax!

Thanks for making this fun and entertaining game live again, but it seems like the server is down for the moment. A lot of stuff like the places and the cut scenes are not working. Are there any plans to open them up again?

If not, could you add some documentation on how to self host the server? This project is really cool and I hope that you keep on improving it 👍 A lot of my friends are interested in this also 🙂

**Comment by MrBrax** [comment]
Server seems to be up. They're not affected by the connection, it's just the multiplayer part.

And no, i couldn't find a good way to animate cutscenes, so i pretty much stopped there.

**Comment by Jacalz** [comment]
I remember that the cutscenes used to work, I really hope you keep this going...

**Comment by Jacalz** [comment]
Looks like the multiplayer wasn't working on the school network, that's why it wasn't working for any of my friends or me. I thught that you had turned off multiplayer, sorry for that 😓

**Comment by MrBrax** [comment]
Makes sense, some proxies can't handle websockets

**Comment by Jacalz** [comment]
It sadly wasn’t anything I thought of at the time...

**Comment by Jacalz** [comment]
Is the server down for real now? Seems like I can't connect to multiplayer anywhere any more :(

**Comment by MrBrax** [comment]
Seems like it crashed. Started it again.

**Comment by Jacalz** [comment]
Thank you :)
Btw, is the server running the latest version of this repo or is it running https://github.com/datagutten/mulle.js?

**Comment by MrBrax** [comment]
latest repo version with a custom censoring filter, project is pretty much dead otherwise
